export const InputNames = {
  NAME: "NAME",
  PROFESSION: "PROFESSION",
  ABOUTYOU: "ABOUTYOU",
  EMAIL: "EMAIL",
  LINKEDIN: "LINKEDIN",
  LOCATION: "LOCATION",
  NUMBER: "NUMBER",
  TWITER: "TWITER",
  INSTA: "INSTA",
  EXPERTISEINPUTS: "EXPERTISEINPUTS",
  ADDEXPERTISEINPUT: "ADDEXPERTISEINPUT",
};
